version: "3.9"
services:
  db:
    restart: always
    image: "postgres:alpine"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: microblog
    ports:
      - "5432:5432"