version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        mvn_arg: clean package -DskipTests
    ports:
      - "8080:8080"
      - "5005:5005"
    volumes:
    - .:/app
    networks:
      - internal_network
      - external_network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    restart: "no"
    depends_on:
      - db
  redis:
    restart: always
    image: "redis:alpine"
    networks:
      - internal_network
  db:
    restart: always
    image: "postgres:alpine"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: microblog
    networks:
      - internal_network
networks:
  internal_network:
    internal: true
  external_network:


