logging:
  level:
    .org:
      springframework: INFO
    .com:
      zaxxer: DEBUG
      root: ERROR
---
spring:
  flyway:
    enabled: false
  datasource:
    url: jdbc:postgresql://192.168.1.155:5432/miniblog
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  jackson:
    default-property-inclusion: non_null
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    prefix: classpath:static/
  cache:
    type: redis
  redis:
    host: 192.168.1.155
    port: 6379
---
spring:
  profiles: generatesql
  flyway:
    enabled: false
  jpa:
    properties:
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: create
              create-target: src/main/resources/ddl_jpa_creation.sql
---
server:
  port: 8443
  ssl:
    key-store-type: JKS
    key-store: classpath:keystore/ssl-server.jks
    key-store-password: merlee
    key-store-provider: SUN
    key-alias: selfsigned_localhost_sslserver