logging:
  level:
    .org:
      springframework: INFO
    .com:
      zaxxer: DEBUG
      root: ERROR
---
#okta:
#  oauth2:
#    issuer: https://dev-9494393.okta.com/oauth2/default
#    client-id: 0oa4ykyvgf245acIH5d6
#    client-secret: 1md7vusN_0yk-0PWUD8Cp8eYvqSfmwkepArwkg3G
#    redirect-uri: /authorization-code/callback
---
support.email: extremelywealthnigerianprince@gmail.com
---
spring:
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB
  flyway:
    enabled: false
  datasource:
    url: jdbc:postgresql://matamercerpi.local:5432/microblog
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  jackson:
    default-property-inclusion: non_null
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    prefix: classpath:/static/templates/
  cache:
    type: redis
  redis:
    host: matamercerpi.local
    port: 6379
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 4f55d5da9e6f66fdd842
            client-secret: 03300ce199a222a968c17e7fbf3f4cb4af0001ab
  mail:
    host: smtp.gmail.com
    port: 465
    protocol: smtps
    username: extremelywealthynigerianprince@gmail.com
    password: 9KJ;`k6e.?&=f^.m~H/~
    transport:
      protocol: smtps
    smtps:
      auth: true
      starttls:
        enable: true
      timeout: 8000
---
#spring:
#  profiles: docker
#  redis:
#    host: redis
#    port: 6379
#  datasource:
#    url: jdbc:postgresql://db:5432/microblog
#    username: postgres
#    password: password
---
spring:
  profiles: dev
  redis:
    host: redis
    port: 6379
  datasource:
    url: jdbc:postgresql://192.168.1.155:5432/microblog
    username: postgres
    password: password
---
spring:
  profiles: generatesql
  flyway:
    enabled: false
  jpa:
    properties:
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: create
              create-target: src/main/resources/ddl_jpa_creation.sql
---
server:
  port: 8443
  ssl:
    key-store-type: JKS
    key-store: classpath:keystore/ssl-server.jks
    key-store-password: merlee
    key-store-provider: SUN
    key-alias: selfsigned_localhost_sslserver