support.email: extremelywealthnigerianprince@gmail.com
---
spring:
  mvc:
    throw-exception-if-no-handler-found: true
  banner:
    image:
      location: banner.txt
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB
  flyway:
    enabled: true
    locations: classpath:/db/migration,classpath:/db/testdata
    baseline-on-migrate: true
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/microblog
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
  jackson:
    default-property-inclusion: non_null
  cache:
    type: redis
  redis:
    host: redis
    port: 6379
  mail:
    host: smtp.gmail.com
    port: 465
    protocol: smtps
    username: extremelywealthynigerianprince@gmail.com
    password: 9KJ;`k6e.?&=f^.m~H/~
    transport:
      protocol: smtps
    smtps:
      auth: true
      starttls:
        enable: true
      timeout: 8000
---
spring:
  redis:
    host: redis
    port: 6379
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/microblog
    username: postgres
    password: password
  config:
    activate:
      on-profile: prod
---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
  flyway:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: create-drop