logging:
  level:
    .org:
      springframework: INFO
    .com:
      zaxxer: DEBUG
      root: ERROR
---
support.email: extremelywealthnigerianprince@gmail.com
---
spring:
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB
  flyway:
    enabled: false
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/microblog
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  jackson:
    default-property-inclusion: non_null
  cache:
    type: redis
  redis:
    host: redis
    port: 6379
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 4f55d5da9e6f66fdd842
            client-secret: 03300ce199a222a968c17e7fbf3f4cb4af0001ab
  mail:
    host: smtp.gmail.com
    port: 465
    protocol: smtps
    username: extremelywealthynigerianprince@gmail.com
    password: 9KJ;`k6e.?&=f^.m~H/~
    transport:
      protocol: smtps
    smtps:
      auth: true
      starttls:
        enable: true
      timeout: 8000
---
#spring:
#  profiles: docker
#  redis:
#    host: redis
#    port: 6379
#  datasource:
#    url: jdbc:postgresql://db:5432/microblog
#    username: postgres
#    password: password
---
spring:
  profiles: dev
  redis:
    host: redis
    port: 6379
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/microblog
    username: postgres
    password: password
---
spring:
  profiles: generatesql
  flyway:
    enabled: false
  jpa:
    properties:
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: create
              create-target: src/main/resources/ddl_jpa_creation.sql