create table authority (id int8 generated by default as identity, created_at timestamp not null, updated_at timestamp not null, authority_string text, user_id int8 not null, primary key (id))
create table posts (id int8 generated by default as identity, created_at timestamp not null, updated_at timestamp not null, content text, user_id int8, primary key (id))
create table users (id int8 generated by default as identity, created_at timestamp not null, updated_at timestamp not null, is_account_non_expired boolean not null, is_account_non_locked boolean not null, is_credentials_non_expired boolean not null, is_enabled boolean not null, password varchar(255) not null, username varchar(255), primary key (id))
alter table if exists users add constraint UK_r43af9ap4edm43mmtq01oddj6 unique (username)
alter table if exists authority add constraint FKka37hl6mopj61rfbe97si18p8 foreign key (user_id) references users
alter table if exists posts add constraint FK5lidm6cqbc7u4xhqpxm898qme foreign key (user_id) references users
