CREATE TABLE likes
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP with time zone                NOT NULL,
    updated_at TIMESTAMP with time zone                NOT NULL,
    fk_liker   BIGINT,
    fk_post    BIGINT,
    CONSTRAINT pk_likes PRIMARY KEY (id)
);

ALTER TABLE follows
    ADD fk_followee_blog BIGINT;

ALTER TABLE follows
    ADD fk_follower_blog BIGINT;

ALTER TABLE follows
    ADD muted BOOLEAN;

ALTER TABLE follows
    ADD notifications_enabled BOOLEAN;

ALTER TABLE follows
    ADD CONSTRAINT FK_FOLLOWS_ON_FK_FOLLOWEE_BLOG FOREIGN KEY (fk_followee_blog) REFERENCES blogs (id);

ALTER TABLE follows
    ADD CONSTRAINT FK_FOLLOWS_ON_FK_FOLLOWER_BLOG FOREIGN KEY (fk_follower_blog) REFERENCES blogs (id);

ALTER TABLE likes
    ADD CONSTRAINT FK_LIKES_ON_FK_LIKER FOREIGN KEY (fk_liker) REFERENCES blogs (id);

ALTER TABLE likes
    ADD CONSTRAINT FK_LIKES_ON_FK_POST FOREIGN KEY (fk_post) REFERENCES posts (id);

ALTER TABLE follows
    DROP CONSTRAINT fk_follows_on_fk_liker;

ALTER TABLE follows
    DROP CONSTRAINT fk_follows_on_fk_post;

ALTER TABLE follows
    DROP COLUMN fk_liker;

ALTER TABLE follows
    DROP COLUMN fk_post;